### ISSUE TITLE
Jack Henry ProfitStars

### ISSUE THREAD

**Issue by astoimenov** [jdavidbakr/laravel-profitstars#3]
Can you tell me which is the Jack Henry ProfitStars payment solution that I need to subscribe for, in order to use the ACH functionality of the package?

**Comment by jdavidbakr** [comment]
It should be this company https://www.profitstars.com/

We already had an account with them prior to setting up our online system (we use them for check scanning) so I can't really help you as far as setting up an account, but I would imagine there would be contact information on that website.  We -may- have had it set up through our bank rather than directly with them.
